PATH = {
    'DATA': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/TRAIN',
    'DATA_MXNET': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/TRAIN_MXNET',
    'DATA_OUT': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/TRAIN_OUT',
    'DATA_TRICKY': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/TRAIN_OUT/TRICKY_SLICES',
    'DATA_ENHANCED': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/TRAIN_ENHS',
    'CSV': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/CSV',
    'LABELS': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/CSV/stage1_labels.csv',
    'SAMPLE': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/CSV/stage1_sample_submission.csv',
    'COMBINED': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/TRAIN_OUT/COMBINED',
    'ENHANCED_CROPPED': '/fasthome/a.dobrenkii/PATCHES/CROPPED',
    'ENHANCED_PREDICTED': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/TRAIN_OUT/DATAFRAMES',

    'LUNA': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA',
    'LUNA_DATA': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/DATA',
    'LUNA_SOBEL': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/SOBEL_IMG',
    'LUNA_LUNGS': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/LUNGS_IMG',
    'LUNA_OUT': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/DATA_OUT',
    'LUNA_TRICKY':'/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/DATA_OUT/TRICKY_SLICES',
    'LUNA_MASKS': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/OUT/MASKS',
    'LUNA_CSV': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/CSVFILES',
    'LUNA_PRED': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/PRED',
    'PATCH_PATCHES': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/OUT/PATCHES',
    'LUNA_NODULES': '/fasthome/a.dobrenkii/PATCHES/NODULES',
    'LUNA_VESSELS': '/fasthome/a.dobrenkii/PATCHES/VESSELS',
    'LUNA_MXNET': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/OUT/MXNET',
    'LUNA_VESSELS_WOR': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/OUT/PATCHES/VESSELS_WOR', 
    'LUNA_NODULES_WOR': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LUNA/OUT/PATCHES/NODULES_WOR', 
    
    'STAGE_DATA': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/NEW_STAGE/DATA', 
    'STAGE_MASKS': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/NEW_STAGE/MASKS', 
    'STAGE_ENHANCED': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/NEW_STAGE/ENHANCED', 
    
    'LOGDIR': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/LOGS', 
    'WEIGHTS': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data/WEIGHTS',
    'CHECKPOINTS': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/data',
    'EVALUATION': '/home/a.dobrenkii/Projects/Kaggle/DataScienceBowl2K17/I/LungCancerDetection/support/evaluationScript'
}
